# auto scaler drivers
obj-$(CONFIG_SCALER_AUTO_I2C)		+= scaler-i2c.o
obj-$(CONFIG_SCALER_AUTO_SPI)		+= scaler-spi.o
obj-$(CONFIG_SCALER_AUTO_UART)		+= scaler-uart.o
obj-$(CONFIG_SCALER_AUTO)			+= chips/
obj-$(CONFIG_SCALER_AUTO)			+= scaler-auto.o