obj-$(CONFIG_SCALER_DP703)					+= dp703.o
obj-$(CONFIG_SCALER_DP703_FIRMWARE_SPI)				+= dp703-firmware-spi.o
obj-$(CONFIG_SCALER_DP703_FIRMWARE_I2C)				+= dp703-firmware-i2c.o
obj-$(CONFIG_SCALER_TV5735)					+= tv5735.o
obj-$(CONFIG_SCALER_TV5930)					+= tv5930.o
